# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TraceMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import SwiftMessage_pb2 as SwiftMessage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TraceMessage.proto',
  package='swift.protocol',
  syntax='proto2',
  serialized_options=_b('\n!com.alibaba.search.swift.protocol'),
  serialized_pb=_b('\n\x12TraceMessage.proto\x12\x0eswift.protocol\x1a\x12SwiftMessage.proto\"\x9b\x01\n\x0cTraceMessage\x12\r\n\x05msgId\x18\x01 \x01(\x03\x12\x16\n\x0brequestUuid\x18\x02 \x01(\x04:\x01\x30\x12\x19\n\x11timestampInSecond\x18\x03 \x01(\r\x12\x18\n\ruint16Payload\x18\x04 \x01(\r:\x01\x30\x12\x1b\n\x10uint8MaskPayload\x18\x05 \x01(\r:\x01\x30\x12\x12\n\x07\x64\x61taLen\x18\x06 \x01(\r:\x01\x30\"\x9d\x01\n\nReaderInfo\x12\x11\n\ttopicName\x18\x01 \x01(\x0c\x12\x10\n\x08\x63lientId\x18\x02 \x01(\x0c\x12\x10\n\x08readerId\x18\x03 \x01(\x0c\x12\n\n\x02ip\x18\x04 \x01(\x0c\x12\x0b\n\x03pid\x18\x05 \x01(\r\x12&\n\x06\x66ilter\x18\x06 \x01(\x0b\x32\x16.swift.protocol.Filter\x12\x17\n\x0bpartitionId\x18\x07 \x01(\x05:\x02-1\"x\n\x11WriteTraceMessage\x12.\n\nreaderInfo\x18\x01 \x01(\x0b\x32\x1a.swift.protocol.ReaderInfo\x12\x33\n\rtraceMessages\x18\x02 \x03(\x0b\x32\x1c.swift.protocol.TraceMessage\"c\n\x12WriteErrorResponse\x12.\n\nreaderInfo\x18\x01 \x01(\x0b\x32\x1a.swift.protocol.ReaderInfo\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\"\xc3\x01\n\x14WriteTraceMessageOld\x12\x11\n\ttopicName\x18\x01 \x01(\x0c\x12\x10\n\x08\x63lientId\x18\x02 \x01(\x0c\x12\x10\n\x08readerId\x18\x03 \x01(\x0c\x12\n\n\x02ip\x18\x04 \x01(\x0c\x12\x0b\n\x03pid\x18\x05 \x01(\r\x12&\n\x06\x66ilter\x18\x06 \x01(\x0b\x32\x16.swift.protocol.Filter\x12\x33\n\rtraceMessages\x18\x07 \x03(\x0b\x32\x1c.swift.protocol.TraceMessageB#\n!com.alibaba.search.swift.protocol')
  ,
  dependencies=[SwiftMessage__pb2.DESCRIPTOR,])




_TRACEMESSAGE = _descriptor.Descriptor(
  name='TraceMessage',
  full_name='swift.protocol.TraceMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgId', full_name='swift.protocol.TraceMessage.msgId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestUuid', full_name='swift.protocol.TraceMessage.requestUuid', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestampInSecond', full_name='swift.protocol.TraceMessage.timestampInSecond', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uint16Payload', full_name='swift.protocol.TraceMessage.uint16Payload', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uint8MaskPayload', full_name='swift.protocol.TraceMessage.uint8MaskPayload', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataLen', full_name='swift.protocol.TraceMessage.dataLen', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=214,
)


_READERINFO = _descriptor.Descriptor(
  name='ReaderInfo',
  full_name='swift.protocol.ReaderInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topicName', full_name='swift.protocol.ReaderInfo.topicName', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientId', full_name='swift.protocol.ReaderInfo.clientId', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='readerId', full_name='swift.protocol.ReaderInfo.readerId', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='swift.protocol.ReaderInfo.ip', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid', full_name='swift.protocol.ReaderInfo.pid', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filter', full_name='swift.protocol.ReaderInfo.filter', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='partitionId', full_name='swift.protocol.ReaderInfo.partitionId', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=374,
)


_WRITETRACEMESSAGE = _descriptor.Descriptor(
  name='WriteTraceMessage',
  full_name='swift.protocol.WriteTraceMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='readerInfo', full_name='swift.protocol.WriteTraceMessage.readerInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='traceMessages', full_name='swift.protocol.WriteTraceMessage.traceMessages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=496,
)


_WRITEERRORRESPONSE = _descriptor.Descriptor(
  name='WriteErrorResponse',
  full_name='swift.protocol.WriteErrorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='readerInfo', full_name='swift.protocol.WriteErrorResponse.readerInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='swift.protocol.WriteErrorResponse.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='swift.protocol.WriteErrorResponse.content', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=597,
)


_WRITETRACEMESSAGEOLD = _descriptor.Descriptor(
  name='WriteTraceMessageOld',
  full_name='swift.protocol.WriteTraceMessageOld',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topicName', full_name='swift.protocol.WriteTraceMessageOld.topicName', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientId', full_name='swift.protocol.WriteTraceMessageOld.clientId', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='readerId', full_name='swift.protocol.WriteTraceMessageOld.readerId', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='swift.protocol.WriteTraceMessageOld.ip', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid', full_name='swift.protocol.WriteTraceMessageOld.pid', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filter', full_name='swift.protocol.WriteTraceMessageOld.filter', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='traceMessages', full_name='swift.protocol.WriteTraceMessageOld.traceMessages', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=600,
  serialized_end=795,
)

_READERINFO.fields_by_name['filter'].message_type = SwiftMessage__pb2._FILTER
_WRITETRACEMESSAGE.fields_by_name['readerInfo'].message_type = _READERINFO
_WRITETRACEMESSAGE.fields_by_name['traceMessages'].message_type = _TRACEMESSAGE
_WRITEERRORRESPONSE.fields_by_name['readerInfo'].message_type = _READERINFO
_WRITETRACEMESSAGEOLD.fields_by_name['filter'].message_type = SwiftMessage__pb2._FILTER
_WRITETRACEMESSAGEOLD.fields_by_name['traceMessages'].message_type = _TRACEMESSAGE
DESCRIPTOR.message_types_by_name['TraceMessage'] = _TRACEMESSAGE
DESCRIPTOR.message_types_by_name['ReaderInfo'] = _READERINFO
DESCRIPTOR.message_types_by_name['WriteTraceMessage'] = _WRITETRACEMESSAGE
DESCRIPTOR.message_types_by_name['WriteErrorResponse'] = _WRITEERRORRESPONSE
DESCRIPTOR.message_types_by_name['WriteTraceMessageOld'] = _WRITETRACEMESSAGEOLD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TraceMessage = _reflection.GeneratedProtocolMessageType('TraceMessage', (_message.Message,), {
  'DESCRIPTOR' : _TRACEMESSAGE,
  '__module__' : 'TraceMessage_pb2'
  # @@protoc_insertion_point(class_scope:swift.protocol.TraceMessage)
  })
_sym_db.RegisterMessage(TraceMessage)

ReaderInfo = _reflection.GeneratedProtocolMessageType('ReaderInfo', (_message.Message,), {
  'DESCRIPTOR' : _READERINFO,
  '__module__' : 'TraceMessage_pb2'
  # @@protoc_insertion_point(class_scope:swift.protocol.ReaderInfo)
  })
_sym_db.RegisterMessage(ReaderInfo)

WriteTraceMessage = _reflection.GeneratedProtocolMessageType('WriteTraceMessage', (_message.Message,), {
  'DESCRIPTOR' : _WRITETRACEMESSAGE,
  '__module__' : 'TraceMessage_pb2'
  # @@protoc_insertion_point(class_scope:swift.protocol.WriteTraceMessage)
  })
_sym_db.RegisterMessage(WriteTraceMessage)

WriteErrorResponse = _reflection.GeneratedProtocolMessageType('WriteErrorResponse', (_message.Message,), {
  'DESCRIPTOR' : _WRITEERRORRESPONSE,
  '__module__' : 'TraceMessage_pb2'
  # @@protoc_insertion_point(class_scope:swift.protocol.WriteErrorResponse)
  })
_sym_db.RegisterMessage(WriteErrorResponse)

WriteTraceMessageOld = _reflection.GeneratedProtocolMessageType('WriteTraceMessageOld', (_message.Message,), {
  'DESCRIPTOR' : _WRITETRACEMESSAGEOLD,
  '__module__' : 'TraceMessage_pb2'
  # @@protoc_insertion_point(class_scope:swift.protocol.WriteTraceMessageOld)
  })
_sym_db.RegisterMessage(WriteTraceMessageOld)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
