# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Transport.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from arpc.proto import rpc_extensions_pb2 as arpc_dot_proto_dot_rpc__extensions__pb2
from . import BrokerRequestResponse_pb2 as BrokerRequestResponse__pb2
from . import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Transport.proto',
  package='swift.protocol',
  syntax='proto2',
  serialized_options=_b('\n!com.alibaba.search.swift.protocol\200\001\001\210\001\001\220\001\001'),
  serialized_pb=_b('\n\x0fTransport.proto\x12\x0eswift.protocol\x1a\x1f\x61rpc/proto/rpc_extensions.proto\x1a\x1b\x42rokerRequestResponse.proto\x1a\x0c\x43ommon.proto2\xee\x03\n\x0bTransporter\x12W\n\ngetMessage\x12\".swift.protocol.ConsumptionRequest\x1a\x1f.swift.protocol.MessageResponse\"\x04\xc0>\xb5\x10\x12W\n\x0bsendMessage\x12!.swift.protocol.ProductionRequest\x1a\x1f.swift.protocol.MessageResponse\"\x04\xc0>\xb6\x10\x12\\\n\x0fgetMaxMessageId\x12 .swift.protocol.MessageIdRequest\x1a!.swift.protocol.MessageIdResponse\"\x04\xc0>\xb7\x10\x12\x62\n\x15getMinMessageIdByTime\x12 .swift.protocol.MessageIdRequest\x1a!.swift.protocol.MessageIdResponse\"\x04\xc0>\xb8\x10\x12\x65\n\x0esetLoggerLevel\x12%.swift.protocol.SetLoggerLevelRequest\x1a&.swift.protocol.SetLoggerLevelResponse\"\x04\xc0>\xb9\x10\x1a\x04\xc0>\xb4\x10\x42,\n!com.alibaba.search.swift.protocol\x80\x01\x01\x88\x01\x01\x90\x01\x01')
  ,
  dependencies=[arpc_dot_proto_dot_rpc__extensions__pb2.DESCRIPTOR,BrokerRequestResponse__pb2.DESCRIPTOR,Common__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_TRANSPORTER = _descriptor.ServiceDescriptor(
  name='Transporter',
  full_name='swift.protocol.Transporter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\300>\264\020'),
  serialized_start=112,
  serialized_end=606,
  methods=[
  _descriptor.MethodDescriptor(
    name='getMessage',
    full_name='swift.protocol.Transporter.getMessage',
    index=0,
    containing_service=None,
    input_type=BrokerRequestResponse__pb2._CONSUMPTIONREQUEST,
    output_type=BrokerRequestResponse__pb2._MESSAGERESPONSE,
    serialized_options=_b('\300>\265\020'),
  ),
  _descriptor.MethodDescriptor(
    name='sendMessage',
    full_name='swift.protocol.Transporter.sendMessage',
    index=1,
    containing_service=None,
    input_type=BrokerRequestResponse__pb2._PRODUCTIONREQUEST,
    output_type=BrokerRequestResponse__pb2._MESSAGERESPONSE,
    serialized_options=_b('\300>\266\020'),
  ),
  _descriptor.MethodDescriptor(
    name='getMaxMessageId',
    full_name='swift.protocol.Transporter.getMaxMessageId',
    index=2,
    containing_service=None,
    input_type=BrokerRequestResponse__pb2._MESSAGEIDREQUEST,
    output_type=BrokerRequestResponse__pb2._MESSAGEIDRESPONSE,
    serialized_options=_b('\300>\267\020'),
  ),
  _descriptor.MethodDescriptor(
    name='getMinMessageIdByTime',
    full_name='swift.protocol.Transporter.getMinMessageIdByTime',
    index=3,
    containing_service=None,
    input_type=BrokerRequestResponse__pb2._MESSAGEIDREQUEST,
    output_type=BrokerRequestResponse__pb2._MESSAGEIDRESPONSE,
    serialized_options=_b('\300>\270\020'),
  ),
  _descriptor.MethodDescriptor(
    name='setLoggerLevel',
    full_name='swift.protocol.Transporter.setLoggerLevel',
    index=4,
    containing_service=None,
    input_type=Common__pb2._SETLOGGERLEVELREQUEST,
    output_type=Common__pb2._SETLOGGERLEVELRESPONSE,
    serialized_options=_b('\300>\271\020'),
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSPORTER)

DESCRIPTOR.services_by_name['Transporter'] = _TRANSPORTER

Transporter = service_reflection.GeneratedServiceType('Transporter', (_service.Service,), dict(
  DESCRIPTOR = _TRANSPORTER,
  __module__ = 'Transport_pb2'
  ))

Transporter_Stub = service_reflection.GeneratedServiceStubType('Transporter_Stub', (Transporter,), dict(
  DESCRIPTOR = _TRANSPORTER,
  __module__ = 'Transport_pb2'
  ))


# @@protoc_insertion_point(module_scope)
